import _IdAndCreatedAtTimestampAndLastModifiedTimestamp from "./_IdAndCreatedAtTimestampAndLastModifiedTimestamp";
export default class _IdAndCreatedAtTimestampAndLastModifiedTimestampAndUserAccountId extends _IdAndCreatedAtTimestampAndLastModifiedTimestamp {
    userAccountId: string;
}
