export declare const MAX_INT_VALUE = 2147483647;
export declare class Lengths {
    static readonly _1: number;
    static readonly _2: number;
    static readonly _4: number;
    static readonly _8: number;
    static readonly _16: number;
    static readonly _32: number;
    static readonly _64: number;
    static readonly _128: number;
    static readonly _256: number;
    static readonly _512: number;
    static readonly _1024: number;
    static readonly _1K: number;
    static readonly _2K: number;
    static readonly _4K: number;
    static readonly _8K: number;
    static readonly _16K: number;
    static readonly _32K: number;
    static readonly _64K: number;
    static readonly _128K: number;
    static readonly _256K: number;
    static readonly _512K: number;
    static readonly _1024K: number;
    static readonly _1M: number;
    static readonly _2M: number;
    static readonly _3M: number;
    static readonly _4M: number;
    static readonly _5M: number;
    static readonly _6M: number;
    static readonly _7M: number;
    static readonly _8M: number;
    static readonly _9M: number;
    static readonly _10M: number;
    static readonly _16M: number;
    static readonly _32M: number;
    static readonly _64M: number;
    static readonly _128M: number;
    static readonly _256M: number;
    static readonly _512M: number;
}
export declare class Values {
    static readonly _24 = 24;
    static readonly _25 = 25;
    static readonly _50 = 50;
    static readonly _100 = 100;
    static readonly _200 = 200;
    static readonly _250 = 250;
    static readonly _500 = 500;
    static readonly _1K = 1000;
    static readonly _10K = 10000;
    static readonly _100K = 100000;
    static readonly _1M = 1000000;
    static readonly _10M = 10000000;
    static readonly _100M = 100000000;
    static readonly _1B = 1000000000;
}
export declare class HttpStatusCodes {
    static readonly SUCCESS = 200;
    static readonly ERRORS_START = 300;
    static readonly MOVED_PERMANENTLY = 301;
    static readonly NOT_MODIFIED = 304;
    static readonly CLIENT_ERRORS_START = 400;
    static readonly BAD_REQUEST = 400;
    static readonly FORBIDDEN = 403;
    static readonly NOT_FOUND = 404;
    static readonly CONFLICT = 409;
    static readonly INTERNAL_ERRORS_START = 500;
    static readonly INTERNAL_SERVER_ERROR = 500;
    static readonly SERVICE_UNAVAILABLE = 503;
}
